-- MySQL Script generated by MySQL Workbench
-- Tue May  2 15:08:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EnxamePhobosDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EnxamePhobosDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EnxamePhobosDB` DEFAULT CHARACTER SET utf8 ;
USE `EnxamePhobosDB` ;

-- -----------------------------------------------------
-- Table `EnxamePhobosDB`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnxamePhobosDB`.`TipoUsuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnxamePhobosDB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnxamePhobosDB`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Senha` CHAR(6) NOT NULL,
  `DataNascUsuario` DATE NOT NULL,
  `TipoUsuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_TipoUsuario_idx` (`TipoUsuario_id` ASC),
  CONSTRAINT `fk_Usuario_TipoUsuario`
    FOREIGN KEY (`TipoUsuario_id`)
    REFERENCES `EnxamePhobosDB`.`TipoUsuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnxamePhobosDB`.`Classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnxamePhobosDB`.`Classificacao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnxamePhobosDB`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnxamePhobosDB`.`Genero` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnxamePhobosDB`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnxamePhobosDB`.`Filme` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(150) NOT NULL,
  `Produtora` VARCHAR(150) NOT NULL,
  `UrlImg` VARCHAR(250) NOT NULL,
  `Classificacao_Id` INT NOT NULL,
  `Genero_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Filme_Classificacao1_idx` (`Classificacao_Id` ASC),
  INDEX `fk_Filme_Genero1_idx` (`Genero_Id` ASC),
  CONSTRAINT `fk_Filme_Classificacao1`
    FOREIGN KEY (`Classificacao_Id`)
    REFERENCES `EnxamePhobosDB`.`Classificacao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filme_Genero1`
    FOREIGN KEY (`Genero_Id`)
    REFERENCES `EnxamePhobosDB`.`Genero` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
