-- MySQL Script generated by MySQL Workbench
-- Wed Apr 12 16:45:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EnxamePhobosDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EnxamePhobosDB` ;

-- -----------------------------------------------------
-- Schema EnxamePhobosDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EnxamePhobosDB` DEFAULT CHARACTER SET utf8 ;
USE `EnxamePhobosDB` ;

-- -----------------------------------------------------
-- Table `EnxamePhobosDB`.`TipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnxamePhobosDB`.`TipoUsuario` ;

CREATE TABLE IF NOT EXISTS `EnxamePhobosDB`.`TipoUsuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnxamePhobosDB`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnxamePhobosDB`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `EnxamePhobosDB`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Senha` CHAR(6) NOT NULL,
  `DataNascUsuario` DATE NOT NULL,
  `TipoUsuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_TipoUsuario_idx` (`TipoUsuario_id` ASC),
  CONSTRAINT `fk_Usuario_TipoUsuario`
    FOREIGN KEY (`TipoUsuario_id`)
    REFERENCES `EnxamePhobosDB`.`TipoUsuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


select*from Usuario;

